sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t jbdiop/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jbdiop/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: docker-react-dev
  env: "Dockerreactdev-env"
  bucket_name: "elasticbeanstalk-us-west-2-538130761021"
  bucket_path: "docker-react-dev"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
